#!/storage/home/gzr5209/.conda/envs/mypython3/bin/python3.9
# -*- coding: utf-8 -*-
import re
import sys
from gcn.cmdline import listen_main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(listen_main())
